name: Cloudflare 优选 IP 自动化

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时运行
  workflow_dispatch:  # 支持手动触发

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 检查代码规范
        run: |
          pip install flake8
          flake8 src/ --max-line-length=120 --exclude=__init__.py

      - name: 运行单元测试
        run: |
          pip install pytest pytest-asyncio
          pytest src/ --verbose

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行优选 IP 脚本
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          python src/main.py

      - name: 上传日志
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: optimizer-logs
          path: cloudflare-optimizer.log
          retention-days: 7
